name: Build Checks

on: push

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: install dependencies
        run: yarn

      - name: build
        run: yarn electron-forge make

  build-win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: install dependencies
        run: yarn

      - name: build
        run: yarn electron-forge make
