name: Build macOS

on:
  push:
    branches:
    - release/production

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: install dependencies
      run: yarn

    - name: build all architectures
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: DEBUG=electron-packager yarn electron-forge publish --arch=all